name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: git clone https://github.com/asdf-vm/asdf.git
      - run: . asdf/asdf.sh
      - run: asdf plugin add krab https://github.com/qbart/asdf-krab.git
      - run: asdf install krab 0.2.2
      - run: asdf global krab 0.2.2

      - name: test
        run: krab version
